spring.application.name=Gestion_Tourisme
spring.datasource.url=jdbc:mysql://localhost:3306/tourism 
spring.datasource.username=root
spring.datasource.password=
#spring.datasource.driver-class-nam
spring.jpa.hibernate.ddl-auto=update
server.port=8083

jwt.secret=MaCleTresLongueEtSuperSecurisee123456
jwt.expiration-ms=3600000  


# configuration du dossier où on stocke les images uploadées
file.upload-dir: ./uploads  
#(chemin relatif ./uploads) pour stocker les images uploadées
payment.mode: "SIMULATED"
